<template>
<div>
<!-- firebase登録用にとりあえず作ったやつをおいておく場所-->
    <v-btn @click="createTeamData()">create</v-btn>

</div>
</template>

<script>
export default {
    layout: 'login',
    data(){
        return{
            teamData: {},
            img:""

        }
    },
    methods:{/*あぶなっかしいので一旦けす
        async createTeamData(){
            this.$firestore.collection("Team").doc("wPenfOmOi4Y8ibxERyqzLU63TTe2").get()
            .then(doc => {

                this.$firestore.collection("Team").doc("Nv7y16tkN8NYdjYP6cup3Q4IW363").set(doc.data())
            })
        },*/
        addTeam(){
          const uid = "dOz1WsyLrJZ0CaCDnA0bcKKZ6Wc2"
          this.$firestore.collection("Team").doc(`${uid}`).set({
            finTime:"",
            gameStart:true,
            status:0,
            startTime:"",
            limitTime:"",
            logs:[0],
            mainMission:[
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
              {
                clear:"",
                id:""
              },
            ],
            nowStage:"",
            photos:{},
            point:{
              eventPoint:0,
              mainPoint:0,
              subPoint:0,
              totalPoint:0,
            },
            subStory:{
              caution:{
                cautionOpened:false,
                cautionMess:""
              },
              quiz1:{
                clear:1,
                delieryTime:0,
                recentAnswer:""
              },
              quiz2:{
                clear:0,
                delieryTime:0,
                recentAnswer:""
              },
              quiz3:{
                clear:0,
                delieryTime:0,
                recentAnswer:""
              },
              quiz4:{
                clear:0,
                delieryTime:0,
                recentAnswer:""
              },
              quiz5:{
                clear:0,
                delieryTime:0,
                recentAnswer:""
              },
            }
          })
        },
        alterTeam(){
          const uid = this.$auth.currentUser.uid
          firestore.doc(`Team/${uid}`).get()
            .then(doc => {
                const nowScore = doc.data().subStory
                nowScore.quiz1.clear = 2
                firestore.doc(`Team/${uid}`).update({subStory: nowScore})
                console.log({nowScore})
            })
        }
    }
  }
</script>

addTeam(){
        const uid = this.$auth.currentUser.uid
        this.$firestore.doc(`Team/${uid}`).set({
          finTime:"",
          gameStart:false,
          status:0,
          startTime:"",
          limitTime:"",
          logs:[0],
          mainMission:{
            0:{
              clear:"",
              id:""
            },
            1:{
              clear:"",
              id:""
            },
            2:{
              clear:"",
              id:""
            },
            3:{
              clear:"",
              id:""
            },
            4:{
              clear:"",
              id:""
            },
            5:{
              clear:"",
              id:""
            },
            6:{
              clear:"",
              id:""
            },
            7:{
              clear:"",
              id:""
            },
            8:{
              clear:"",
              id:""
            },
            9:{
              clear:"",
              id:""
            },
            10:{
              clear:"",
              id:""
            },
            11:{
              clear:"",
              id:""
            },
            12:{
              clear:"",
              id:""
            },
            13:{
              clear:"",
              id:""
            },
            14:{
              clear:"",
              id:""
            },
            15:{
              clear:"",
              id:""
            },
            16:{
              clear:"",
              id:""
            },
            17:{
              clear:"",
              id:""
            },
            18:{
              clear:"",
              id:""
            },
            19:{
              clear:"",
              id:""
            },
            20:{
              clear:"",
              id:""
            },
            21:{
              clear:"",
              id:""
            },
            22:{
              clear:"",
              id:""
            },
            23:{
              clear:"",
              id:""
            },
            24:{
              clear:"",
              id:""
            },
            25:{
              clear:"",
              id:""
            },
            26:{
              clear:"",
              id:""
            },
            27:{
              clear:"",
              id:""
            },
            28:{
              clear:"",
              id:""
            },
            29:{
              clear:"",
              id:""
            },
          },
          nowStage:"",
          photos:{},
          point:{
            eventPoint:0,
            mainPoint:0,
            subPoint:0,
            totalPoint:0,
          },
          subStory:{
            quiz1:{
              clear:1,
              delieryTime:0,
              recentAnswer:""
            },
            quiz2:{
              clear:0,
              delieryTime:0,
              recentAnswer:""
            },
            quiz3:{
              clear:0,
              delieryTime:0,
              recentAnswer:""
            },
            quiz4:{
              clear:0,
              delieryTime:0,
              recentAnswer:""
            },
            quiz5:{
              clear:0,
              delieryTime:0,
              recentAnswer:""
            },
          }
        })
